In [197]:
import numpy as np
import pandas as pd
import re
a=np.array([1,2,3])
print(a)
b=np.array([[1,4,3,6],[2,4,9,3]])
print(b)

[1 2 3]
[[1 4 3 6]
 [2 4 9 3]]


Get Dimension

In [198]:
b.ndim

2

Get Shape

In [199]:
b.shape

(2, 4)

Accessing rows/columns

In [200]:
b[0,:]

array([1, 4, 3, 6])

In [201]:
print(b)
b[0,3]=1
print(b)

[[1 4 3 6]
 [2 4 9 3]]
[[1 4 3 1]
 [2 4 9 3]]


In [202]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [203]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
c=np.matmul(a,b)
print(c)
np.cos(a)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


array([[0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231]])

In [204]:
import pandas as pd
df=pd.read_csv('/Users/pranavahari/documents/Pokemon_data.csv')
df.head(3)


#       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
0  1  Bulbasaur  Grass  Poison  45      49       49       65       65     45   
1  2    Ivysaur  Grass  Poison  60      62       63       80       80     60   
2  3   Venusaur  Grass  Poison  80      82       83      100      100     80   

   Generation  Legendary  
0           1      False  
1           1      False  
2           1      False

In [205]:
# Read each column
print(df['Name'])
print(df[['Name','HP']])
# Read each row
print(df.iloc[0:4])
# Read a value in specific row and column(R,C)
print(df.iloc[2,3])


0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...          
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object
                      Name  HP
0                Bulbasaur  45
1                  Ivysaur  60
2                 Venusaur  80
3    VenusaurMega Venusaur  80
4               Charmander  39
..                     ...  ..
795                Diancie  50
796    DiancieMega Diancie  50
797    HoopaHoopa Confined  80
798     HoopaHoopa Unbound  80
799              Volcanion  80

[800 rows x 2 columns]
   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65   
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3              

In [206]:
df.loc[df['Type 1']=="Grass"]

#                   Name Type 1    Type 2   HP  Attack  Defense  \
0      1              Bulbasaur  Grass    Poison   45      49       49   
1      2                Ivysaur  Grass    Poison   60      62       63   
2      3               Venusaur  Grass    Poison   80      82       83   
3      3  VenusaurMega Venusaur  Grass    Poison   80     100      123   
48    43                 Oddish  Grass    Poison   45      50       55   
..   ...                    ...    ...       ...  ...     ...      ...   
718  650                Chespin  Grass       NaN   56      61       65   
719  651              Quilladin  Grass       NaN   61      78       95   
720  652             Chesnaught  Grass  Fighting   88     107      122   
740  672                 Skiddo  Grass       NaN   66      65       48   
741  673                 Gogoat  Grass       NaN  123     100       62   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
48        75       65     30           1      False  
..       ...      ...    ...         ...        ...  
718       48       45     38           6      False  
719       56       58     57           6      False  
720       74       75     64           6      False  
740       62       57     52           6      False  
741       97       81     68           6      False  

[70 rows x 12 columns]

Sorting and describing data

In [207]:
df.describe

<bound method NDFrame.describe of        #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45       

Making changes to data

In [208]:
#add values usinng column name
df['Total']=df['HP']+df['Attack']+df['Defense']
df.head(2)

#Drop a column
#df=df.drop(columns='Total')
#df.head(2)

#Add horizontally using indexes
#df['Total']=df.iloc[:,4:10].sum(axis=1)
#df.head(3)

# Adding a row
df._append({'Name':'Pingu'}, ignore_index=True)

#Drop a row
# df.drop(index=)

#sort values
df.sort_values('Name',ascending=False)
cols=list(df.columns.values)
df=df[cols[0:4]+[cols[-1]]+cols[4:12]]
df

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    143  45      49       49   
1      2                Ivysaur    Grass  Poison    185  60      62       63   
2      3               Venusaur    Grass  Poison    245  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    303  80     100      123   
4      4             Charmander     Fire     NaN    134  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    300  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    320  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    250  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    300  80     160       60   
799  721              Volcanion     Fire   Water    310  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

Filtering Data using loc and iloc

In [209]:
df.loc[8]

#                                     6
Name          CharizardMega Charizard Y
Type 1                             Fire
Type 2                           Flying
Total                               260
HP                                   78
Attack                              104
Defense                              78
Sp. Atk                             159
Sp. Def                             115
Speed                               100
Generation                            1
Legendary                         False
Name: 8, dtype: object

In [210]:
#loc uses labels to search data
print(df.loc[4,'Attack'])

print(df.loc[4])

print(df.loc[:,'Type 1'])
#Filter by creating highpower variable
Highpower=(df['Attack'] & df['Sp. Atk'])>50

df[Highpower]
# Filter to get specific columns with highpower filter
df.loc[Highpower,['Name','Type 1','Type 2']]

#Different Example
filt=df['Name'].str.contains('saur',na=False)
df.loc[filt,'Name']
#filter based on names strating with 'pi' using rregex functions
dilt= df['Name'].str.contains('^pi[a-z]',flags=re.I,regex=True)
df[dilt]

#Conditional changes or setting value(here we change all the fire entries to flame in type 1)
df.loc[df['Type 1']=='Fire','Type 1']='Flame'
df.loc[df['Total']>300,['Generation','Legendary']]=['New','Mythic']
df.loc[df['Total']>300]


52
#                      4
Name          Charmander
Type 1              Fire
Type 2               NaN
Total                134
HP                    39
Attack                52
Defense               43
Sp. Atk               60
Sp. Def               50
Speed                 65
Generation             1
Legendary          False
Name: 4, dtype: object
0        Grass
1        Grass
2        Grass
3        Grass
4         Fire
        ...   
795       Rock
796       Rock
797    Psychic
798    Psychic
799       Fire
Name: Type 1, Length: 800, dtype: object


#                       Name  Type 1   Type 2  Total   HP  Attack  \
3      3      VenusaurMega Venusaur   Grass   Poison    303   80     100   
7      6  CharizardMega Charizard X   Flame   Dragon    319   78     130   
12     9    BlastoiseMega Blastoise   Water      NaN    302   79     103   
82    76                      Golem    Rock   Ground    330   80     120   
87    80        SlowbroMega Slowbro   Water  Psychic    350   95      75   
..   ...                        ...     ...      ...    ...  ...     ...   
792  716                    Xerneas   Fairy      NaN    352  126     131   
793  717                    Yveltal    Dark   Flying    352  126     131   
794  718           Zygarde50% Forme  Dragon   Ground    329  108     100   
796  719        DiancieMega Diancie    Rock    Fairy    320   50     160   
799  721                  Volcanion   Flame    Water    310   80     110   

     Defense  Sp. Atk  Sp. Def  Speed Generation Legendary  
3        123      122      120     80        New    Mythic  
7        111      130       85    100        New    Mythic  
12       120      135      115     78        New    Mythic  
82       130       55       65     45        New    Mythic  
87       180      130       80     30        New    Mythic  
..       ...      ...      ...    ...        ...       ...  
792       95      131       98     99        New    Mythic  
793       95      131       98     99        New    Mythic  
794      121       81       95     95        New    Mythic  
796      110      160      110    110        New    Mythic  
799      120      130       90     70        New    Mythic  

[94 rows x 13 columns]

In [219]:
#Using Groupby
df.groupby(['Type 1']).count()


RangeIndex(start=0, stop=800, step=1)

In [ ]:
#we can simply use the filter variable with df if we want all columns
df[filt]

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    143  45      49       49   
1  2                Ivysaur  Grass  Poison    185  60      62       63   
2  3               Venusaur  Grass  Poison    245  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    303  80     100      123   

   Sp. Atk  Sp. Def  Speed Generation Legendary  
0       65       65     45          1     False  
1       80       80     60          1     False  
2      100      100     80          1     False  
3      122      120     80        New    Mythic

In [ ]:
df.loc[(df['Type 1']=="Grass") & (df['Type 2']=="Poison")]

#                   Name Type 1  Type 2  Total   HP  Attack  Defense  \
0      1              Bulbasaur  Grass  Poison    143   45      49       49   
1      2                Ivysaur  Grass  Poison    185   60      62       63   
2      3               Venusaur  Grass  Poison    245   80      82       83   
3      3  VenusaurMega Venusaur  Grass  Poison    303   80     100      123   
48    43                 Oddish  Grass  Poison    150   45      50       55   
49    44                  Gloom  Grass  Poison    195   60      65       70   
50    45              Vileplume  Grass  Poison    240   75      80       85   
75    69             Bellsprout  Grass  Poison    160   50      75       35   
76    70             Weepinbell  Grass  Poison    205   65      90       50   
77    71             Victreebel  Grass  Poison    250   80     105       65   
344  315                Roselia  Grass  Poison    155   50      60       45   
451  406                  Budew  Grass  Poison    105   40      30       35   
452  407               Roserade  Grass  Poison    195   60      70       65   
651  590                Foongus  Grass  Poison    169   69      55       45   
652  591              Amoonguss  Grass  Poison    269  114      85       70   

     Sp. Atk  Sp. Def  Speed Generation Legendary  
0         65       65     45          1     False  
1         80       80     60          1     False  
2        100      100     80          1     False  
3        122      120     80        New    Mythic  
48        75       65     30          1     False  
49        85       75     40          1     False  
50       110       90     50          1     False  
75        70       30     40          1     False  
76        85       45     55          1     False  
77       100       70     70          1     False  
344      100       80     65          3     False  
451       50       70     55          4     False  
452      125      105     90          4     False  
651       55       55     15          5     False  
652       85       80     30          5     False

In [ ]:
#iloc uses indexes instead of labels
print(df.iloc[:,1])
#using lists (R,C)
print(df.iloc[[0,2],[3,4]])

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...          
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object
   Type 2  Total
0  Poison    143
2  Poison    245
